default: connected.png copy.png build_run.png git.png Makefile README my_beaglebone.jpg
	tar -czvf lab4a-204585474.tar.gz connected.png copy.png build_run.png git.png Makefile README my_beaglebone.jpg
